### ISSUE TITLE
crypto-random-string

### ISSUE THREAD

**Issue by keverw** [lukehaas/RunJS#244]
I'm trying to run this module, and it seems to throw an error. https://github.com/sindresorhus/crypto-random-string

```
import cryptoRandomString from 'crypto-random-string';

cryptoRandomString({length: 10, type: 'alphanumeric'});
// cryptoRandomString({length: 10});
 ```

Sounds like an older version of `crypto-random-string` had that "Expected a finite number" but running newer versions shouldn't... and even if I go remove the package and reload, I still get that error... So it's running the package without it being installed some how... I even manually checked `/Library/Application Support/runjs/node_modules`

A bit puzzled here. Wonder if it's loading that module globally instead since it seems popular from maybe a system utility or your own project uses it internally and there's a conflict? Using Version 1.15.1 (1.15.1) of RunJS

**Comment by lukehaas** [comment]
Thanks for raising this. You're right, `crypto-random-string` is an internal dependency of RunJS and that's how you're seeing this.
I'm aware of the issue but haven't yet got around to resolving it. I'll aim it get it sorted for the next release.

**Comment by lukehaas** [comment]
This is now resolved in the latest version of RunJS

**Comment by keverw** [comment]
I just upgraded to try this. Getting "Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:" I figured maybe since I noticed you charge now, so went ahead and paid since I love this tool to try to deal with code more real-time and still getting this issue... I wonder if because my file name is `something.ts"? 

```
import cryptoRandomString from 'crypto-random-string';

cryptoRandomString({length: 10, type: 'alphanumeric'});
```

I wonder if because of the way it's being transpiled maybe?

Also I love you added tabs, it would be nice if we could right click and "Reveal in Finder" like JS code.

**Comment by lukehaas** [comment]
Seems to be due to the latest version of the package only supporting ESM imports.
Please install the previous version of it, version 3.3.1:

![Screenshot 2021-07-05 at 09 40 06](https://user-images.githubusercontent.com/741344/124443192-60cea680-dd75-11eb-94bb-e695ea2b7655.png)

**Comment by keverw** [comment]
Yep that works. Interesting.

Wonder if more and more node packages are going to start requiring that? I was trying to import a markdown package in my mono repo (outside of RunJS), so think the same issue for both. Not sure how that would work, was trying to change my project into a "module" in the root package and it just ended up breaking a lot of things with the config and stuff.
